"use client"
import Link from "next/link"
import { usePathname } from "next/navigation"
import { Bell, CalendarDays, CheckSquare, ChevronLeft, FileText, LayoutDashboard, Menu, MoreHorizontal, Search, Settings, Sparkles, UserRound, X } from "lucide-react"
import { useState } from "react"
import { cn } from "@/lib/utils"
import { Button, Badge } from "@/components/ui"
const nav = [{href:"/dashboard",label:"Dashboard",icon:LayoutDashboard},{href:"/ai",label:"Omni AI",icon:Sparkles},{href:"/search",label:"Search",icon:Search},{href:"/tasks",label:"Tasks",icon:CheckSquare},{href:"/notes",label:"Notes",icon:FileText},{href:"/calendar",label:"Calendar",icon:CalendarDays}]
const secondary = [{href:"/reminders",label:"Reminders",icon:Bell},{href:"/analytics",label:"Analytics",icon:MoreHorizontal},{href:"/automations",label:"Automations",icon:Sparkles}]
function NavLink({item,onClick}:{item:any;onClick?:()=>void}) { const path=usePathname(); const active=path===item.href; const Icon=item.icon; return <Link onClick={onClick} href={item.href} className={cn("flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm transition-colors",active?"bg-muted font-medium text-foreground":"text-muted-foreground hover:bg-muted hover:text-foreground")}><Icon className="size-4" />{item.label}</Link> }
export function Shell({children}:{children:React.ReactNode}) { const [open,setOpen]=useState(false); return <div className="min-h-screen bg-background"><aside className={cn("fixed inset-y-0 left-0 z-30 hidden w-64 flex-col border-r bg-card px-4 py-5 lg:flex",open&&"flex") }><div className="flex items-center justify-between px-2"><Link href="/" className="flex items-center gap-2 font-semibold tracking-tight"><span className="grid size-8 place-items-center rounded-xl bg-primary text-primary-foreground"><Sparkles className="size-4"/></span>OmniDash</Link><button className="rounded-lg p-2 text-muted-foreground lg:hidden" onClick={()=>setOpen(false)} aria-label="Close menu"><X className="size-4"/></button></div><div className="mt-8 flex flex-1 flex-col gap-1">{nav.map(i=><NavLink key={i.href} item={i} onClick={()=>setOpen(false)}/>)}<div className="my-4 border-t"/>{secondary.map(i=><NavLink key={i.href} item={i} onClick={()=>setOpen(false)}/>)}</div><div className="flex flex-col gap-1 border-t pt-4">{[{href:"/notifications",label:"Notifications",icon:Bell},{href:"/settings",label:"Settings",icon:Settings},{href:"/profile",label:"Profile",icon:UserRound}].map(i=><NavLink key={i.href} item={i}/>)}</div></aside><div className="lg:pl-64"><header className="sticky top-0 z-20 flex h-16 items-center justify-between border-b bg-background/95 px-4 backdrop-blur sm:px-6"><button className="rounded-lg p-2 lg:hidden" onClick={()=>setOpen(true)} aria-label="Open menu"><Menu className="size-5"/></button><div className="hidden text-sm text-muted-foreground lg:block">Tuesday, September 16, 2026</div><div className="ml-auto flex items-center gap-2"><Button variant="ghost" className="hidden sm:inline-flex"><Search className="size-4"/>Search</Button><Link href="/notifications" className="rounded-xl p-2.5 text-muted-foreground hover:bg-muted" aria-label="Notifications"><Bell className="size-4"/></Link><Link href="/profile" className="grid size-9 place-items-center rounded-full bg-accent text-sm font-medium text-accent-foreground">OS</Link></div></header><main className="min-h-[calc(100vh-4rem)] px-4 pb-24 pt-6 sm:px-6 lg:px-10 lg:pb-10">{children}</main></div><nav className="fixed inset-x-3 bottom-3 z-20 flex items-center justify-around rounded-2xl border bg-card/95 p-2 shadow-lg backdrop-blur lg:hidden">{nav.slice(0,5).map(i=><Link key={i.href} href={i.href} className="flex min-w-12 flex-col items-center gap-1 rounded-xl px-2 py-1.5 text-[10px] text-muted-foreground"><i.icon className="size-4"/>{i.label}</Link>)}<Link href="/ai" className="-mt-7 grid size-14 place-items-center rounded-full border-4 border-background bg-primary text-primary-foreground shadow-lg" aria-label="Open Omni AI"><Sparkles className="size-5"/></Link></nav></div> }
