import * as React from "react"
import { cn } from "@/lib/utils"

export function Button({ className, variant="primary", ...props }: React.ButtonHTMLAttributes<HTMLButtonElement> & { variant?: "primary" | "secondary" | "ghost" }) { return <button className={cn("inline-flex min-h-10 items-center justify-center gap-2 rounded-xl px-4 text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50", variant === "primary" && "bg-primary text-primary-foreground hover:opacity-90", variant === "secondary" && "bg-muted text-foreground hover:bg-border", variant === "ghost" && "text-muted-foreground hover:bg-muted hover:text-foreground", className)} {...props} /> }
export function Card({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) { return <div className={cn("rounded-2xl border bg-card shadow-[0_1px_2px_rgba(16,24,40,.03)]", className)} {...props} /> }
export function Input({ className, ...props }: React.InputHTMLAttributes<HTMLInputElement>) { return <input className={cn("h-11 w-full rounded-xl border bg-background px-3 text-sm outline-none placeholder:text-muted-foreground focus:ring-2 focus:ring-ring", className)} {...props} /> }
export function Badge({ className, children }: React.HTMLAttributes<HTMLSpanElement>) { return <span className={cn("inline-flex items-center rounded-full bg-accent px-2.5 py-1 text-xs font-medium text-accent-foreground", className)}>{children}</span> }
export function Skeleton({ className }: { className?: string }) { return <div className={cn("animate-pulse rounded-lg bg-muted", className)} /> }
export function EmptyState({ title, description, action }: { title: string; description: string; action?: React.ReactNode }) { return <div className="flex min-h-64 flex-col items-center justify-center rounded-2xl border border-dashed p-8 text-center"><div className="mb-4 size-10 rounded-xl bg-accent" /><h3 className="font-semibold">{title}</h3><p className="mt-2 max-w-sm text-sm text-muted-foreground">{description}</p>{action && <div className="mt-5">{action}</div>}</div> }
